apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.rollouts.name }}
  labels:
    {{- include "nodejs.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.selector }}
    spec:
      {{- with .Values.hostAliases }}
      hostAliases:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
      {{ toYaml .Values.nodeSelector | indent 2 }}
      containers:
        - name: {{ .Values.selector }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "80"
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #     scheme: HTTP
          #   initialDelaySeconds: 300
          #   timeoutSeconds: 10
          #   periodSeconds: 30
          #   successThreshold: 1
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #     scheme: HTTP
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 10
          #   periodSeconds: 20
          #   successThreshold: 1
          #   failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.containerport }}
  strategy:
    blueGreen:
      autoPromotionEnabled: true
      activeService: {{ .Values.service.service.name }}
      previewService: {{ .Values.service.servicepreview.name }}
