{{- if .Values.secrets.enabled -}}
apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
data:
  .dockerconfigjson: {{ .Values.secrets.data }}
{{- end }}
